export enum CategoriesName {
  "resolution" = "Разрешение",
  "focalLength" = "Фокусное расстояние",
  "microphone" = "Микрофон",
  "dynamic" = "Динамик",
  "memoryСard" = "Поддержка карты памяти",
  "wifi" = "Wi-Fi",
}

export enum AllCatigoriesName {
  "title" = "Наименование модели",
  "resolution" = "Разрешение",
  "focalLength" = "Фокусное расстояние",
  "microphone" = "Микрофон",
  "dynamic" = "Динамик",
  "memoryСard" = "Поддержка карты памяти",
  "wifi" = "Wi-Fi",
  "property0" = "Свойство 1",
}

export const productsData = [
  {
    id: "0",
    categories: "outdoor",
    title: "FC-B4WFH-36-M",
    property0: "Металлический, степень пылевлагозащиты IP67",
    property1: "property1",
    property2: "property2",
    resolution: "4MP", // Разрешение
    focalLength: "3.6mm", // Фокусное расстояние
    microphone: "с микрофоном", // микрофон
    dynamic: "с динамиком", // Динамик
    memoryСard: "поддерживает", // поддержка карты памяти
    wifi: "да",
  },
  {
    id: "1",
    categories: "outdoor",
    title: "Test 2",
    property0: "property0",
    property1: "property1",
    property2: "property2",
    resolution: "Test 2",
    focalLength: "??? ???",
    microphone: "с микрофоном",
    dynamic: "без динамика",
    memoryСard: "поддерживает",
    wifi: "нет",
  },
  {
    id: "2",
    categories: "indoor",
    title: "Test 3",
    property0: "property0",
    property1: "property1",
    property2: "property2",
    resolution: "Test 3",
    focalLength: "???",
    microphone: "без микрофона",
    dynamic: "без динамика",
    memoryСard: "не поддерживает",
    wifi: "да",
  },
  {
    id: "3",
    categories: "equipment",
    title: "Test 4",
    property0: "property0",
    property1: "property1",
    property2: "property2",
    resolution: "Test 4",
    focalLength: "???",
    microphone: "с микрофоном",
    dynamic: "с динамиком",
    memoryСard: "не поддерживает",
    wifi: "да",
  },
  {
    id: "4",
    categories: "equipment",
    title: "Test 5",
    property0: "property0",
    property1: "property1",
    property2: "property2",
    resolution: "Test 5",
    focalLength: "???",
    microphone: "без микрофона",
    dynamic: "с динамиком",
    memoryСard: "поддерживает",
    wifi: "да",
  },
  {
    id: "5",
    categories: "equipment",
    title: "Test 6",
    property0: "property0",
    property1: "property1",
    property2: "property2",
    resolution: "Test 6",
    focalLength: "???",
    microphone: "с микрофоном",
    dynamic: "с динамиком",
    memoryСard: "не поддерживает",
    wifi: "нет",
  },
  {
    id: "6",
    categories: "equipment",
    title: "Test 7",
    property0: "property0",
    property1: "property1",
    property2: "property2",
    resolution: "Test 7",
    focalLength: "???",
    microphone: "без микрофона",
    dynamic: "с динамиком",
    memoryСard: "поддерживает",
    wifi: "да",
  },
];
